site_name: Gabriel Tsurushima
site_description: My personal website!
site_url: https://tsurubr.github.io/

# THEME ------------------------------------------------------------------------
theme:
  name: material
  language: en
  favicon: images/frog-solid.png
  icon:
    logo: fontawesome/solid/frog
    #logo: fontawesome/solid/robot
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    # - content.template
  
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: teal
      accent: orange

# NAVIGATION -------------------------------------------------------------------
nav:
  # - Testes: test.md
  - Home: index.md
  - My Heroes: my-heroes.md
  - Estudo:
    - Q1.25:
      - AR1: Quads/Q1.25/AR1.md
      - MDO: Quads/Q1.25/MDO.md
      - TDG: Quads/Q1.25/TDG.md
    - Q3.24:
      - ALA: Quads/Q3.24/ALA.md
      - CDP: Quads/Q3.24/CDP.md
      - NRES: Quads/Q3.24/NRES.md
      - AP: Quads/Q3.24/AP.md
  - Utilidades: utilidades.md
  - Escrivinhações:
    - Desigualdade de Cauchy-Schwarz: Cauchy-Schwarz.md

plugins:
  - social
  - search
  # - blog

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  css:
    - css/custom.css
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tsurubr
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gabriel.tsurushima
      
copyright: |
  &copy; 2025 <a href="https://github.com/tsurubr"  target="_blank" rel="noopener">Gabriel Tsurushima</a>
